# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-06-04 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AtomPressSensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('deviceStatus', models.BooleanField()),
                ('deviceId', models.IntegerField()),
                ('atomPress', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'verbose_name_plural': '大气压力传感器(HumiditySensor)',
            },
        ),
        migrations.CreateModel(
            name='FloodlightSensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('deviceStatus', models.BooleanField()),
                ('deviceId', models.IntegerField()),
                ('luminance', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'verbose_name_plural': '光照传感器(FloodlightSensor)',
            },
        ),
        migrations.CreateModel(
            name='HumiditySensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('deviceStatus', models.BooleanField()),
                ('deviceId', models.IntegerField()),
                ('humidity', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'verbose_name_plural': '湿度传感器(HumiditySensor)',
            },
        ),
        migrations.CreateModel(
            name='TemperatureSensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('deviceStatus', models.BooleanField()),
                ('deviceId', models.IntegerField()),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'verbose_name_plural': '温度传感器(TemperatureSensor)',
            },
        ),
    ]
