# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-01-10 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Can',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('deviceStatus', models.BooleanField()),
                ('deviceId', models.IntegerField()),
                ('luminance', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'verbose_name_plural': 'Can总线设备(10-13)',
            },
        ),
        migrations.CreateModel(
            name='ModbusRtu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('deviceStatus', models.BooleanField()),
                ('deviceId', models.IntegerField()),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'verbose_name_plural': 'MoudbusRtu设备(0-9)',
            },
        ),
        migrations.CreateModel(
            name='ModbusTcp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('deviceStatus', models.BooleanField()),
                ('deviceId', models.IntegerField()),
                ('humidity', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'verbose_name_plural': 'ModbusTcp设备(14-15)',
            },
        ),
        migrations.CreateModel(
            name='RaspberryPi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('deviceStatus', models.BooleanField()),
                ('deviceId', models.IntegerField()),
                ('atomPress', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'verbose_name_plural': 'RaspberryPi设备(16-17)',
            },
        ),
    ]
