# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-01-10 13:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IOTEWMPApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='can',
            old_name='luminance',
            new_name='realtimeData',
        ),
        migrations.RenameField(
            model_name='modbusrtu',
            old_name='temperature',
            new_name='realtimeData',
        ),
        migrations.RenameField(
            model_name='modbustcp',
            old_name='humidity',
            new_name='realtimeData',
        ),
        migrations.RenameField(
            model_name='raspberrypi',
            old_name='atomPress',
            new_name='realtimeData',
        ),
    ]
